@startuml

interface GuiFactory {
Button createButton()
Panel createPanel()
}

GuiFactory <|-- WindowsFactory
GuiFactory <|-- LinuxFactory

enum OS {
WINDOWS
LINUX
}

class GuiFactorySelector {
GuiFactory getFactory(OS os)
}

interface Component {
void paint()
}
interface Panel
interface Button

Component <|-- Button
Component <|-- Panel

Button <|-- WindowsButton
Button <|--- LinuxButton

Panel <|-- WindowsPanel
Panel <|--- LinuxPanel

GuiFactorySelector --> WindowsFactory
GuiFactorySelector --> LinuxFactory
GuiFactorySelector -r-> OS

WindowsFactory --> WindowsPanel
WindowsFactory --> WindowsButton

LinuxFactory --> LinuxPanel
LinuxFactory --> LinuxButton

note "Retornará el Factory solicitado" as NoteGuiFactorySelector
GuiFactorySelector .. NoteGuiFactorySelector

note "Abstract Factory" as NoteGuiFactory
GuiFactory .. NoteGuiFactory

note "return new WindowsButton()\nreturn new WindowsPanel()" as NoteWindowsFactory
WindowsFactory .r. NoteWindowsFactory

note "return new LinuxButton()\nreturn new LinuxPanel()" as NoteLinuxFactory
LinuxFactory .l. NoteLinuxFactory

@enduml