@startuml

class Person {
String firstName
String lastName
static PersonBuilder builder()
}

class PersonBuilder {
String firstName
String lastName
PersonBuilder firstName(String firstName)
PersonBuilder lastName(String lastName)
Person build()
}

PersonBuilder *-up- Person
PersonBuilder --> Person

note "El método builder() instancia la clase\nbuilder específica para Person" as PersonNote
PersonNote .r. Person

note "public Person build() {\n         return new Person(firstName, lastName);\n}" as PersonBuilderNote
PersonBuilderNote .r. PersonBuilder

@enduml