@startuml

interface CompressionFormat {
    void compress(List<File> files)
}

class Compressor {
	void setCompressionFormat(CompressionFormat compressionFormat)
	void compress(List<File> files)
}

RarCompression -u-|> CompressionFormat
ZipCompression -u-|> CompressionFormat

Compressor *-d- CompressionFormat

@enduml